### ISSUE TITLE
Support for Microsoft Edge

### ISSUE THREAD

**Issue by maver1ck** [ETCExtensions/Edit-This-Cookie#153]
Please add Support for Microsoft Edge Browser.
This could help.
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

**Comment by tuxzz** [comment]
It's very easy! Just load EditThisCookie on edge then it works!
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions
