### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by MikkCZ** [ETCExtensions/Edit-This-Cookie#175]
Hi.

Firefox 57 is out and I think now it's the right time to port this extension for it. The WebExtensions API should be mostly compatible with non-deprecated Chrome APIs, so porting this to Firefox shouldn't be hard. About a month ago they have also change the review process on addons.mozilla.org, so the extensions using the new API are approved and published in few minutes after going through automated checks, and manual review follows later.

**Comment by zidekmat** [comment]
It seems to be ported [here](https://addons.mozilla.org/en-US/firefox/addon/editthiscookieaddon/?src=userprofile), but I'm not sure if it's official by @fcapano or who else did it.

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the add-on development seems stopped anyway.
