### ISSUE TITLE
Cannot manually add cookies

### ISSUE THREAD

**Issue by Blihi** [ETCExtensions/Edit-This-Cookie#237]
The option to manually add a cookie is broken. When clicking the "+ Block Cookie" button, nothing happens. Chrome complains that "size()" is not a function in line 128 of block_rules.js. 

This line is now:    if ($(".new_row:not(.template)").size() > 0) {

It works when changing this to    if ($(".new_row:not(.template)").length > 0) {

**Comment by fcapano** [comment]
Fixed in commit 3c8c9659f6c60dcae0601cb4528228cac6b201aa
